# Custom Language File for Launcher Customizer

[ejs.app]
title = "Aluv Client"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kaonioon/Aluv"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/VE8rfpdtmf"

[ejs.settings]
sourceGithubLink = "https://github.com/Kaonioon/Aluv"
supportLink = "https://github.com/Kaonioon/Aluv/issues"

[ejs.welcome]
welcomeHeader = "Aluv Clientへようこそ"
welcomeDescription = "現在Aluvはベータ版ですが、私達は日々改善に取り組んでおり、これからもっとたくさんの新機能をリリース予定です。ぜひ将来のアップデートでお会いしましょう！"
